# -*- coding: utf-8 -*-
"""aplicativo-streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fr6SeaG7GFFQEtGpcH5MkYOKyXqd5stu
"""

import streamlit as st

def es_primo(n):
    """
    Función para verificar si un número es primo.
    Un número primo es un número natural mayor que 1 que no tiene divisores positivos
    más que 1 y él mismo.
    """
    # Los números primos deben ser mayores que 1.
    if n <= 1:
        return False
    # El 2 es el único número primo par.
    if n == 2:
        return True
    # Si es divisible por 2 (y no es 2), no es primo.
    if n % 2 == 0:
        return False
    # Verificamos divisores impares desde 3 hasta la raíz cuadrada del número.
    # Solo necesitamos comprobar hasta la raíz cuadrada porque si n tiene un divisor
    # mayor que su raíz cuadrada, entonces necesariamente tiene un divisor
    # más pequeño que su raíz cuadrada.
    i = 3
    while i * i <= n:
        if n % i == 0:
            return False
        i += 2
    return True

# --- Interfaz de Usuario de Streamlit ---

# Título de la aplicación que se mostrará en la web.
st.title('🔢 Verificador de Números Primos')

# Descripción o instrucciones para el usuario.
st.write("Introduce un número entero para saber si es primo o no. Los números primos son aquellos que solo son divisibles por 1 y por sí mismos.")

# Campo de entrada numérico para que el usuario ingrese el número.
# Usamos st.number_input para asegurarnos de que solo se introduzcan números.
# 'min_value=0' para no permitir negativos. 'step=1' para que sean enteros.
numero_usuario = st.number_input('Ingresa un número:', min_value=0, step=1, value=0)

# Botón para iniciar la verificación.
if st.button('Verificar si es primo'):
    # Cuando el usuario haga clic en el botón, se ejecutará este bloque.
    if es_primo(numero_usuario):
        # Si la función devuelve True, mostramos un mensaje de éxito.
        st.success(f"¡El número {numero_usuario} es un número primo! 🎉")
    else:
        # Si la función devuelve False, mostramos un mensaje de advertencia/error.
        st.warning(f"El número {numero_usuario} no es un número primo. 😕")

# Un pequeño pie de página para darle un toque personal.
st.markdown("---")
st.markdown("Creado para la comunidad de Streamlit.")